### ISSUE TITLE
Do we really need all those production dependencies?

### ISSUE THREAD

**Issue by pmario** [tiddly-gittly/watch-fs#5]
Production dependencies are: 

  "dependencies": {
    "chokidar": "^3.5.3",
    "mime": "^3.0.0",
    "npm-check-updates": "^16.10.12",
    "rxjs": "^7.8.1",
    "tiddlywiki": "^5.2.7",
    "tiddlywiki-plugin-dev": "^0.0.36"
  }

Why do we need [npm-check-updates](https://www.npmjs.com/package/npm-check-updates?activeTab=readme) as a production dependency?

For production there should be _no_ automatic update in any way. It needs to be locked until a code-review has been finished.

[rxjs](https://www.npmjs.com/package/rxjs), Why and where are Reactive Extensions need for a **production** TiddlyWiki setup

[tiddlywiki-plugin-dev](https://www.npmjs.com/package/tiddlywiki-plugin-dev) IMO this should be a **dev** dependency when needed.

**Comment by linonetwo** [comment]
Seems     "npm-check-updates": "^16.10.12",  is added by https://github.com/tiddly-gittly/Modern.TiddlyDev , and not everything in `dependencies` will be bundled into /dist.

It only bundled used ones.

But clean `dependencies` up will reduce confusion, so I have done this just now.

You can see, the plugin size is the same.

**Comment by pmario** [comment]
IMO that's much better now. It will be considerably less work to review the stuff.
