### ISSUE TITLE
Plugin installation throws SyntaxError: Cannot import statement outside a modul

### ISSUE THREAD

**Issue by samprintz** [tiddly-gittly/watch-fs#9]
Thank you for your work on this plugin. Could you give me advise how to install it? When follow your instrutions in readme I get:

```
tiddlywiki_1  | Error executing boot module $:/plugins/linonetwo/watch-fs/FileSystemMonitor.js: {}
tiddlywiki_1  |
tiddlywiki_1  | $:/plugins/linonetwo/watch-fs/FileSystemMonitor.js:5
tiddlywiki_1  | import chokidar from 'chokidar';
tiddlywiki_1  | ^^^^^^
tiddlywiki_1  |
tiddlywiki_1  | SyntaxError: Cannot use import statement outside a module
tiddlywiki_1  |     at new Script (node:vm:94:7)
tiddlywiki_1  |     at createScript (node:vm:250:10)
tiddlywiki_1  |     at Object.runInNewContext (node:vm:291:10)
tiddlywiki_1  |     at $tw.utils.evalSandboxed ($:/boot/boot.js:601:5)
tiddlywiki_1  |     at $tw.modules.execute ($:/boot/boot.js:879:15)
tiddlywiki_1  |     at $:/boot/boot.js:919:30
tiddlywiki_1  |     at $tw.utils.each ($:/boot/boot.js:155:12)
tiddlywiki_1  |     at $tw.modules.forEachModuleOfType ($:/boot/boot.js:918:12)
tiddlywiki_1  |     at $tw.boot.execStartup ($:/boot/boot.js:2478:14)
tiddlywiki_1  |     at $tw.boot.startup ($:/boot/boot.js:2497:11)
```

To clarify: I copied the content of `src/watch-fs` to `mywiki/plugins/watch-fs`. I did not update my `tiddlywiki.info`. I tried with and without adding the plugin to my wiki start arguments, it seems to load it also when not added.

**Comment by linonetwo** [comment]
When installing plugins in this Organization, you should install from CPL https://tw-cpl.netlify.app/#Plugin_202310110932256

we don't put anything in /plugins folder, it is hard to upgrade.

**Comment by linonetwo** [comment]
I think this plugin don't handle rename well (not sure), so don't forget to backup.

**Comment by samprintz** [comment]
Thanks, that worked :heavy_check_mark:

**Comment by zigmhount** [comment]
Hi, I'm also having trouble installing this plugin.
I've just created a brand new nodejs wiki (`tiddlywiki mynewwiki --init server`), drag&dropped CPL from https://tw-cpl.netlify.app into it, tried to install `watch-fs` from CPL, and got the error `Error: [404] Cannot find plugin $:/plugins/twcloud/tiddlyweb-sse`.
I went to https://github.com/twcloud/tiddlyweb-sse and installed it (in my wiki's plugin folder, or by passing `++path/to/tiddlyweb-sse/dist/` to the `tiddlywiki` command). I can see that the tiddler `https://github.com/twcloud/tiddlyweb-sse` does exist in my wiki, yet the installation of watch-fs from CPL does still return the same 404 message.

I've tried on machines running linux with nodejs v18, v22 and v23.
Any idea?

**Comment by linonetwo** [comment]
Yes, sse plugin was missing, I've just [fixed that in CPL repo](https://github.com/tiddly-gittly/TiddlyWiki-CPL/commit/7653e83cff28d8a1587857ccb6a85f4bb06b9999). 

And I've push watch-fs v0.2.0 to CPL, you can download it from CPL an hour later.
